version: '2.2'
services:
  jmusicbot:
    container_name: jmusicbot
    restart: unless-stopped
    volumes:
     - ./config:/jmb/config:rw
    image: craumix/jmusicbot
# Remember Download Config In env\JmusicBot floder
# Edit Config and add some parameter