version: '3.3'
services:
  cloudflare:
    restart: always
    container_name: cloudflare
    depends_on:
      - container_name
    command: "tunnel --no-autoupdate run --token {your-token}"
    image: cloudflare/cloudflared