version: '3.3'
services:
  portainer:
    container_name: portainer
    restart: always
    # ports:
    #   - "9000"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './portainer:/data'
    image: portainer/portainer
