version: '3.3'
services:
  portainer:
    # ports:
    #   - "9000"
    restart: always
    container_name: portainer
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './portainer:/data'
    image: portainer/portainer-ce:2.0.1
