version: '3.3'
services:
  pt-portainer:
    ports:
      - "9000"
    restart: always
    container_name: pt-portainer
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './portainer:/data'
    image: portainer/portainer-ce:2.0.1
  pt-cloudflare:
    restart: always
    container_name: pt-cloudflare
    depends_on:
      - pt-portainer
    command: "tunnel --no-autoupdate run --token {your-token}"
    image: cloudflare/cloudflared